apiVersion: v1
kind: Secret
metadata:
    name: registry-secret
    namespace: web-app
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:MOx/pg01IXWaIKYkTfsh7YtJyYLVbUDuqZWj4LiQMzMg6swwiSN5tVEcMDJ7veYi2Xtq8uymAsmpK1lTTliZJw9RwIReAJzf/seVsG/rrn8cj2HITgfLb5312jAffceQg7VE+GslazU2xuu5tfq01ezr+TBfUUCx/Syt7ZY/fdeV4y2MNZFE9Tb3CkUBDGKJ2pjGleHie/BVsHZTRWVTf6v9uTwVYvacRkzawkYPitYUyXStF8lJBsxuHGe4XbA=,iv:2jXKq0FJ8Q9C8fvJ+l+/1G3x9+gyA1JGetSzEZ8QIjk=,tag:z7+tlAD6n9K3mwhhWy7vAw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFmVzQkYHPzSKYjaGaTjEQozp8h2gvRcQkGqX7c2pm0U
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGZEWVhXQSBBak50
            dTVOTjJRNmlJZi9TcG9YNFFIUm0rbFpGbVBkQm04RUJxY1BBTlNjCkRlc1ZnU3pM
            WFJ0MW9HTHg2MFRVekpCc1ppS09rVkxzekV0YmtyUTBjZ1EKLS0tIGpVV1dOVVNO
            NHlTQ2FwRXdjVzRxTE5Xait3ekRGQXEvelZkMjg3RXpCQzAK8Qw6ZCSIs+spWCoD
            yZvivyba6GCwvlk0W06ax2pMy3Jr9+XYBUkIOcI7trfNnSJ1bA9O/cMdPB63/2+Z
            1krXag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T08:09:24Z"
    mac: ENC[AES256_GCM,data:z5pcR2+kmSPb3xSCG3zMjazqDEhr1cByVx9/i7VyXm35dPvqB/Xxjxac04cIlYIC9/eOj7bQMxCDxHEHHEp9qNY2XHXRpOnYNOrSG+rDCHk0QNxL/fNq8czo2qwKM4+vyjwUf9gTE6fLvsr9RcoLPsjbudt/mw10iluLQFYFpnw=,iv:VBgs+Uy8V8CBtYQn+aDgqm6J6I/xmSlYhFtrOnIkWq8=,tag:6efZv1FGDyK0e911vi83hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
