apiVersion: v1
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:LrxQOzXp6KMMQ380Iz49bx99akIl/YsP2E1tHbAq4c0IIRQ9UFG1R3V+RF8=,iv:INpaxwcGo6oY7nMoFzNS2O+oL+y7ns59Q3FUvpmSMko=,tag:/UEQGuIOyyTX7PyStktFWg==,type:str]
    BETTER_AUTH_URL: ENC[AES256_GCM,data:DCnR2gIEeD6VQg2V5ivO1/TGG6gf,iv:Q00DbHMKuq+Jpueua9FArtz1An/ZmmWJfflUFCT0434=,tag:hKUlwt6/kD8l+3AV5YanXw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:7Z2OURjqiHAEisJh0pJtN3KeD+BHVDB72roFf02Ew9CYMKfcdVspQewvQpKbZWrVLkX1rTiQ77gj9iFxNkmnAAeePLV55A==,iv:arkKivYGhYNHciq6WIlRPnMzdO7z21mfjQ4kfjStKT0=,tag:cryV+1ypPyvsOT6fUyMObA==,type:str]
    EMAIL_SMTP_HOST: ENC[AES256_GCM,data:1cG+eQVMMsSq,iv:L+bmmQjjV3sWJiyKrPgSv9y51mEBKWvemn1ENeOO6kA=,tag:zK4R3nNd/pHEgLFBnDDjzQ==,type:str]
    EMAIL_SMTP_PORT: ENC[AES256_GCM,data:pHVcfg==,iv:j5k3qsSIeuRGkCSrZzXmSGWRMyWbaGpKPKVyvZGNwSc=,tag:19nigcz3GYOyJs0mP4iHvQ==,type:str]
    EMAIL_SMTP_SECURE: ENC[AES256_GCM,data:AMfiogk=,iv://JGtbEUMW1CyKQyjqoNBO7/2t7BhIFlFqBEelHHmF8=,tag:E9OedM7vbrXnoj4KMjdU8Q==,type:str]
    GOOGLE_AUTH_CLIENT_ID: ENC[AES256_GCM,data:Sj0ZdXSnx+1AKSXwy1NNX1b7NsvRQmVZ0vbnY0DsEh9Mn/QHQlXATktYzNYAX1+CPwJxDjpOGPM8O4SYJOPjtNLrrITcO+vJIw==,iv:tHoNkB9uBAuvEjFhrmzZIvjtUqLpt6359L3u9YrizLc=,tag:Mz8uri2gjdgzcWg1cZ6siQ==,type:str]
    GOOGLE_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:QeHCDcwgyHpZ3bIR1F0TT57wNw3voHw3GtGwc2dWahylMFA=,iv:NuOs4zPI+YO2ykZcvLX0Qs8azF0zwqoLQV6UDznR8Ho=,tag:ndsI7CWNtcAbcIZM5dLGYA==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:ZLzU4xFlVTJMloCCGNvT1orZZYelYtfX7X3gtdHp0Q==,iv:RXypqPWpp1DJiIB0l49i1Bvp9cN96VfK1zil6AotLpE=,tag:6ukrJ+Ys+4NxkOWJtW/8yw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:bQxpwhPBk+3D,iv:uoFKHK/HAPkmuvQfjeoUKaw1UFG7n6TOCJVgIpNrgbM=,tag:/5i3Eo8vPX/otlx4HT9YDQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:to/DZqfeeVtzWj7QqNajC8c/ujIIGW2z2TLuo2Qi,iv:pSytfSB8XNUy+e3CmcjCENrcKfUjFwcnQCHAl0LnJnY=,tag:2pQltrRf2HVuOulx5nFn5A==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:o7PUnA==,iv:TRVMNtUxZ0ivkNxZC5/iD6DeYdmQj1Ybl7SJNYVgy8E=,tag:UZyMvSJM1BIvVONfJ1PmXA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:dgunkK0=,iv:6MdqB4IH4j1fl9bCKse58G8lJEuhKiep/fiOjFkCFhM=,tag:UWpK8Fl6OfSbmEtjcFtEkQ==,type:str]
    S3_BUCKET_NAME: ENC[AES256_GCM,data:5IUdtxAJ+DfwpK0=,iv:aiSpVyTkf9V2uMEUXb1cTbZ9Oqk3ENxbipNqpcedeVM=,tag:Jhr/6yVd1ac9AzjfQNEHtw==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:NksorEA+MCX7T/MH/BW3JaMv6CFT,iv:POUPhtzBH9mzluQlQAFj/CcRJMSxr+/NdhxklTBlIho=,tag:+4HoczRuUeSOzx26zA25+A==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yPrc,iv:+pfjbYIrwEncPlsJTfsNI79eN/cKWUfJN1b1oQCWctY=,tag:DSnaAaTz2uN3s+bNAuLgsg==,type:str]
kind: Secret
metadata:
    name: web-app-env
    namespace: web-app
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFmVzQkYHPzSKYjaGaTjEQozp8h2gvRcQkGqX7c2pm0U
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGZEWVhXQSBZSVBY
            SEVUZGdwNGUwTnlpeHE0RG9UaVY2ZGVzY0ZTU2xOeUt4bVRnd2p3CmJIUlhtbWp4
            K1pCN2RvU0tjN3NUQmJ2eWpGYTV6Z1JtcVRDUU13Y2RIWDAKLS0tIGMrZDY4R1Bv
            cmV2VnFoc3BrNllEQ29JN2NWRXFnYVFBTUY5SUFUSkJ1djgKFC9mn1bjuE0ccf6Z
            wushG9nUsVI6yhOhsYIxFTjSAmuWyJwgzejwMsm2Qb37SrWtNaSy6gjozE5b1l9k
            0ooAwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T07:40:20Z"
    mac: ENC[AES256_GCM,data:WGt2BEl38q9Q4NyaUQ+3THW6AE3/i00NiDufU2/L5GFUpD+bjvwsoTiy7pgsz4obe7raAAdXG/n8RARHCxlQrEA4C/cfDghJGrB+Q4tBtickbq8VHucPW02mp6YrlzsqhelRoVN2pX2MQYwCHn9593NsHca6/nE5v8THOoACstk=,iv:GsDK/5UkiXZGXhz1kuK51qauvj6cMNUNJb2xR/h/YGg=,tag:0fuZzAtMKe2bPEQWW4/xNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
