services:
  video-processing-service:
    build:
      context: .
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:8.6.1-trixie
    ports:
      - "6379:6379"

networks:
  default:
    name: hr-app-network
    external: true
