services:
  nginx:
    build: ./nginx
    ports:
      - "3001:443"
    volumes:
      - ./data/videos/processed:/usr/share/nginx/html:ro
    
  video-service:
    build: .
    volumes:
      - ./data/:/app/data:rw
