server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    # Redirect all HTTP requests to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;
    http3 on;

    server_name localhost;

    # for now these are self-signed
    # visit the site and write "thisisunsafe" to bypass the warning in chrome for your session
    ssl_certificate /etc/ssl/certs/nginx.crt;
    ssl_certificate_key /etc/ssl/private/nginx.key;
    ssl_protocols TLSv1.3;
    add_header Alt-Svc 'h3=":443"; ma=86400';
    add_header X-Protocol $server_protocol always;

    access_log /var/log/nginx/host.access.log main;

    # # Handle the small segments with other caching strategy than the manifest
    # location ~* ^/api/v1/stream/(.*\.webm)$ {
    #     alias /usr/share/nginx/html/$1;

    #     expires 365d;
    #     add_header Cache-Control "private, immutable";
    #     # CORS Headers
    #     add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
    #     add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
    #     add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
    # }
    # location /api/v1/stream {
    #     alias /usr/share/nginx/html;
    #     # CORS Headers
    #     add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
    #     add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
    #     add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
    # }
    location / {
        proxy_pass http://s3:8333;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_request_buffering off; # Disable request buffering so data streams to Hono immediately
        proxy_buffering off; # Prevent Nginx from buffering the response back from Hono

        client_max_body_size 0; # Disable client body size limit to allow large uploads

        # CORS Headers are handled by seaweedfs s3
    }


    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}

